/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fd761a",
        "primary-fixed": "#dde1ff",
        "secondary": "#9d4300",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "secondary-fixed": "#ffdbca",
        "outline": "#757684",
        "primary": "#00288e",
        "on-surface-variant": "#444653",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#ffb690",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-tint": "#3755c3",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#173bab",
        "on-primary-fixed": "#001453",
        "surface-container": "#eceef0",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-container": "#00563a",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#341100",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "primary-container": "#1e40af",
        "on-secondary-fixed-variant": "#783200",
        "on-tertiary-container": "#3fd298",
        "on-tertiary-fixed": "#002113",
        "on-primary-container": "#a8b8ff",
        "outline-variant": "#c4c5d5",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b8c4ff",
        "on-secondary-container": "#5c2400",
        "inverse-primary": "#b8c4ff",
        "on-error-container": "#93000a",
        "tertiary": "#003d27",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-low": "#f2f4f6"
      },
      spacing: {
        "margin-mobile": "1rem",
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "gutter": "1.5rem",
        "stack-md": "1rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
